{
  "description": null,
  "extensions": {},
  "extensionASTNodes": [],
  "_queryType": "Query",
  "_mutationType": "Mutation",
  "_subscriptionType": "Subscription",
  "_directives": [
    "@cacheControl",
    "@include",
    "@skip",
    "@deprecated",
    "@specifiedBy"
  ],
  "_typeMap": {
    "Query": "Query",
    "ID": "ID",
    "String": "String",
    "Int": "Int",
    "Mutation": "Mutation",
    "Boolean": "Boolean",
    "Subscription": "Subscription",
    "DateTime": "DateTime",
    "PageInfo": "PageInfo",
    "CurrencyCode": "CurrencyCode",
    "Money": "Money",
    "User": "User",
    "UserSearchInput": "UserSearchInput",
    "UserSearchOrganizaton": "UserSearchOrganizaton",
    "SearchedUser": "SearchedUser",
    "UserSearchResult": "UserSearchResult",
    "PlayerMatchData": "PlayerMatchData",
    "PlayerStatus": "PlayerStatus",
    "Event": "Event",
    "Float": "Float",
    "EventStatus": "EventStatus",
    "EventFormatEnum": "EventFormatEnum",
    "RulesEnforcementLevel": "RulesEnforcementLevel",
    "PairingType": "PairingType",
    "LimitedSet": "LimitedSet",
    "EventFilter": "EventFilter",
    "CreateEventInput": "CreateEventInput",
    "UpdateEventInput": "UpdateEventInput",
    "BatchCreateEventsInput": "BatchCreateEventsInput",
    "LocationInput": "LocationInput",
    "BatchCreateResponse": "BatchCreateResponse",
    "EventPage": "EventPage",
    "InProgressEvent": "InProgressEvent",
    "RecurrenceEvent": "RecurrenceEvent",
    "RecurringEventResponse": "RecurringEventResponse",
    "CreateRecurringEventInput": "CreateRecurringEventInput",
    "UpdateRecurringEventInput": "UpdateRecurringEventInput",
    "DeleteRecurringEventInput": "DeleteRecurringEventInput",
    "RecurrenceFrequency": "RecurrenceFrequency",
    "EventFormat": "EventFormat",
    "CardSet": "CardSet",
    "Penalty": "Penalty",
    "Infraction": "Infraction",
    "InfractionCategory": "InfractionCategory",
    "PrivateEvent": "PrivateEvent",
    "JSON": "JSON",
    "Rule": "Rule",
    "Tag": "Tag",
    "EventTemplate": "EventTemplate",
    "OrganizationGroupOption": "OrganizationGroupOption",
    "FieldRuleOption": "FieldRuleOption",
    "TemplateUsage": "TemplateUsage",
    "Organization": "Organization",
    "Incident": "Incident",
    "CreateIncidentInput": "CreateIncidentInput",
    "CreateTeamIncidentInput": "CreateTeamIncidentInput",
    "UpdateIncidentInput": "UpdateIncidentInput",
    "DeleteIncidentInput": "DeleteIncidentInput",
    "Registration": "Registration",
    "Feedback": "Feedback",
    "FeedbackInput": "FeedbackInput",
    "GameStateV2": "GameStateV2",
    "RoundMetadataV2": "RoundMetadataV2",
    "PodV2": "PodV2",
    "DeckConstructionV2": "DeckConstructionV2",
    "DraftV2": "DraftV2",
    "SeatV2": "SeatV2",
    "RoundV2": "RoundV2",
    "MatchV2": "MatchV2",
    "TeamV2": "TeamV2",
    "DropV2": "DropV2",
    "TeamResultV2": "TeamResultV2",
    "TeamStandingV2": "TeamStandingV2",
    "TeamResultInputV2": "TeamResultInputV2",
    "StartPhaseInputV2": "StartPhaseInputV2",
    "Void": "Void",
    "PodPairingTypeV2": "PodPairingTypeV2",
    "SetRoundTimerInputV2": "SetRoundTimerInputV2",
    "EventStartedPayload": "EventStartedPayload",
    "GamekeeperNotificationPayload": "GamekeeperNotificationPayload",
    "GamekeeperResultsTeamResult": "GamekeeperResultsTeamResult",
    "GamekeeperResultsNotificationPayload": "GamekeeperResultsNotificationPayload",
    "GameState": "GameState",
    "RoundMetadata": "RoundMetadata",
    "Pod": "Pod",
    "Seat": "Seat",
    "Round": "Round",
    "Match": "Match",
    "Drop": "Drop",
    "TeamResult": "TeamResult",
    "Team": "Team",
    "TeamStanding": "TeamStanding",
    "MatchResultInput": "MatchResultInput",
    "StartEventInput": "StartEventInput",
    "CertifyRoundInput": "CertifyRoundInput",
    "CertifyRoundPayload": "CertifyRoundPayload",
    "PodPairingType": "PodPairingType",
    "SetRoundTimerInput": "SetRoundTimerInput",
    "PlatformStatus": "PlatformStatus",
    "SetRegisteredPlayerNameInput": "SetRegisteredPlayerNameInput",
    "FailReason": "FailReason",
    "FailedRegistration": "FailedRegistration",
    "BulkImportPlayerResponse": "BulkImportPlayerResponse",
    "RegistrationPayload": "RegistrationPayload",
    "PlayerRegistrationInput": "PlayerRegistrationInput",
    "SetPreferredTableNumberInput": "SetPreferredTableNumberInput",
    "ClearPreferredTableNumberInput": "ClearPreferredTableNumberInput",
    "PlayerRegisteredPayload": "PlayerRegisteredPayload",
    "PlayerDroppedPayload": "PlayerDroppedPayload",
    "RegistrationUpdatedPayload": "RegistrationUpdatedPayload",
    "ReservationNotificationPayload": "ReservationNotificationPayload",
    "TeamPlayerInput": "TeamPlayerInput",
    "TeamPayload": "TeamPayload",
    "OrganizationGroup": "OrganizationGroup",
    "SearchInput": "SearchInput",
    "SearchedOrganization": "SearchedOrganization",
    "OrganizationSearchResult": "OrganizationSearchResult",
    "AcceptTermsAndConditionsInput": "AcceptTermsAndConditionsInput",
    "GroupInput": "GroupInput",
    "WebsiteType": "WebsiteType",
    "PhoneType": "PhoneType",
    "WPNStatus": "WPNStatus",
    "BusinessType": "BusinessType",
    "Brand": "Brand",
    "StoreWebsite": "StoreWebsite",
    "CreateStoreWebsite": "CreateStoreWebsite",
    "UpdateStoreWebsite": "UpdateStoreWebsite",
    "StorePhoneNumber": "StorePhoneNumber",
    "UpdateStorePhoneNumber": "UpdateStorePhoneNumber",
    "CreateStorePhoneNumber": "CreateStorePhoneNumber",
    "CreateBrandInput": "CreateBrandInput",
    "CreateDistributorInput": "CreateDistributorInput",
    "CreateStoreInput": "CreateStoreInput",
    "UpdateStoreInput": "UpdateStoreInput",
    "BatchGroupInput": "BatchGroupInput",
    "BatchGroupFailure": "BatchGroupFailure",
    "BatchGroupResponse": "BatchGroupResponse",
    "RoleName": "RoleName",
    "Role": "Role",
    "RoleInput": "RoleInput",
    "ChangeRoleInput": "ChangeRoleInput",
    "RoleChangedPayload": "RoleChangedPayload",
    "AdminRoleChangedPayload": "AdminRoleChangedPayload",
    "Venue": "Venue",
    "CreateVenueInput": "CreateVenueInput",
    "ApproveVenueInput": "ApproveVenueInput",
    "EditVenueInput": "EditVenueInput",
    "VenueUpdatePayload": "VenueUpdatePayload",
    "SendSMSStatus": "SendSMSStatus",
    "Resp": "Resp",
    "MobileNumberInput": "MobileNumberInput",
    "broadcastSMSInput": "broadcastSMSInput",
    "sendSMSInput": "sendSMSInput",
    "TwilioRoleInput": "TwilioRoleInput",
    "CreatePrivateEventInput": "CreatePrivateEventInput",
    "Language": "Language",
    "Distributor": "Distributor",
    "DbOperation": "DbOperation",
    "AuditRecord": "AuditRecord",
    "AuditRecordGroup": "AuditRecordGroup",
    "AuditRecordResponse": "AuditRecordResponse",
    "PagedInput": "PagedInput",
    "EventSearchSortField": "EventSearchSortField",
    "EventSearchSortDirection": "EventSearchSortDirection",
    "EventSearchQuery": "EventSearchQuery",
    "EventFilterItem": "EventFilterItem",
    "EventFilterGroup": "EventFilterGroup",
    "StoreByLocationInput": "StoreByLocationInput",
    "StorePage": "StorePage",
    "Timer": "Timer",
    "TimerState": "TimerState",
    "CreateTimerInput": "CreateTimerInput",
    "SetTimerInput": "SetTimerInput",
    "CacheControlScope": "CacheControlScope",
    "Upload": "Upload",
    "MagicCardFilterInput": "MagicCardFilterInput",
    "LogicalOperatorFilter": "LogicalOperatorFilter",
    "LogicalOperator": "LogicalOperator",
    "LogicalRarityInput": "LogicalRarityInput",
    "MagicCardRarity": "MagicCardRarity",
    "LogicalManaCostInput": "LogicalManaCostInput",
    "RangeFilterInput": "RangeFilterInput",
    "PrintedLanguage": "PrintedLanguage",
    "LogicalLegalitiesInput": "LogicalLegalitiesInput",
    "MagicCardSortInput": "MagicCardSortInput",
    "SortOrder": "SortOrder",
    "MagicCardSortCriteria": "MagicCardSortCriteria",
    "MagicCardSearchResult": "MagicCardSearchResult",
    "SearchResult": "SearchResult",
    "MagicCard": "MagicCard",
    "MagicCardFace": "MagicCardFace",
    "MagicManaCost": "MagicManaCost",
    "magicCardRelation": "magicCardRelation",
    "MagicCardLegality": "MagicCardLegality",
    "MagicFormat": "MagicFormat",
    "MagicCardLegalStatus": "MagicCardLegalStatus",
    "MagicCardPrinting": "MagicCardPrinting",
    "MagicCardSet": "MagicCardSet",
    "MagicRuling": "MagicRuling",
    "MagicCardPrintingFilterInput": "MagicCardPrintingFilterInput",
    "MagicCardPrintingSearchResult": "MagicCardPrintingSearchResult",
    "magicCardSets": "magicCardSets",
    "magicCardOracleSubType": "magicCardOracleSubType",
    "magicCardOracleSuperType": "magicCardOracleSuperType",
    "magicCardPrintingsArtist": "magicCardPrintingsArtist",
    "__Schema": "__Schema",
    "__Type": "__Type",
    "__TypeKind": "__TypeKind",
    "__Field": "__Field",
    "__InputValue": "__InputValue",
    "__EnumValue": "__EnumValue",
    "__Directive": "__Directive",
    "__DirectiveLocation": "__DirectiveLocation"
  },
  "_subTypeMap": {},
  "_implementationsMap": {
    "SearchResult": {
      "objects": [
        "MagicCardSearchResult",
        "MagicCardPrintingSearchResult"
      ],
      "interfaces": []
    }
  }
}
